"""Task foreign keys

Revision ID: 440caa4f4e01
Revises: 51c0570aa30e
Create Date: 2019-01-21 17:26:27.587417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '440caa4f4e01'
down_revision = '51c0570aa30e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('node_id', sa.Integer(), nullable=False))
    op.add_column('task', sa.Column('task_group_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'task', 'task_group', ['task_group_id'], ['id'])
    op.create_foreign_key(None, 'task', 'node', ['node_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_column('task', 'task_group_id')
    op.drop_column('task', 'node_id')
    # ### end Alembic commands ###
